---
title: Logistic Regression with Stock Returns
author: Aaron Hardy
date: '2021-09-13'
slug: logistic-regression-with-stock-returns
categories: []
tags: []
description: 'Modeling stock returns with logistic regression'
featured: ''
featuredalt: ''
featuredpath: ''
linktitle: ''
output:
      blogdown::html_page:
            highlight: tango
            toc: true
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>
<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<div id="TOC">
<ul>
<li><a href="#summary">Summary</a></li>
<li><a href="#load-data-and-packages">Load data and packages</a></li>
<li><a href="#the-data">The data</a></li>
<li><a href="#exploratory-data-analysis">Exploratory data analysis</a>
<ul>
<li><a href="#missing-data">Missing data</a></li>
</ul></li>
<li><a href="#variable-selection">Variable selection</a>
<ul>
<li><a href="#feature-variables">Feature variables</a></li>
<li><a href="#response-variable">Response variable</a></li>
</ul></li>
<li><a href="#data-cleaning">Data cleaning</a>
<ul>
<li><a href="#data-balance">Data balance</a></li>
<li><a href="#clean-up-outliers">Clean Up Outliers</a></li>
</ul></li>
<li><a href="#statistical-modeling">Statistical modeling</a>
<ul>
<li><a href="#split-the-data-into-training-and-test-sets">Split the data into training and test sets</a></li>
</ul></li>
<li><a href="#interpret-results">Interpret results</a></li>
<li><a href="#final-model">Final Model</a>
<ul>
<li><a href="#model-predictions">Model predictions</a></li>
<li><a href="#model-evaluation">Model evaluation</a></li>
</ul></li>
<li><a href="#final-results">Final results</a></li>
<li><a href="#discussion">Discussion</a></li>
</ul>
</div>

<hr />
<div id="summary" class="section level2">
<h2>Summary</h2>
<p>The goal of this analysis is to fit a
<a href="https:://en.m.wikipedia.org/wiki/Logistic_regression">logistic
model</a>
to data containing financial variables
in an attempt to predict future stock
price returns. We will look at a group
of companies in the technology sector
and attempt to forecast their six-month
forward stock returns. We will use
financial data from the companies’
public financial statements.</p>
</div>
<div id="load-data-and-packages" class="section level2">
<h2>Load data and packages</h2>
<p>First, we’ll load external libraries and
the data.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the data</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>ratios_data <span class="ot">&lt;-</span> </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">read_csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/aaron-san/invest-with-r/master/csv/ratios_final.csv&quot;</span>, <span class="at">col_types =</span> <span class="fu">cols</span>())</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>ratios_long <span class="ot">&lt;-</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>      ratios_data <span class="sc">%&gt;%</span> </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>      <span class="fu">pivot_longer</span>(<span class="sc">-</span><span class="fu">c</span>(ticker, fundamentals_date, sector_yhoo), <span class="at">names_to =</span> <span class="st">&quot;field&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;value&quot;</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of tickers</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>ratios_long <span class="sc">%&gt;%</span> <span class="fu">distinct</span>(ticker) <span class="sc">%&gt;%</span> <span class="fu">nrow</span>()</span></code></pre></div>
<pre><code>## [1] 1192</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of fields</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>ratios_long <span class="sc">%&gt;%</span> <span class="fu">distinct</span>(field) <span class="sc">%&gt;%</span> <span class="fu">nrow</span>()</span></code></pre></div>
<pre><code>## [1] 11</code></pre>
</div>
<div id="the-data" class="section level2">
<h2>The data</h2>
<p>The original data is a time series of
1,192 tickers and
11
financial variables.</p>
<p>We must make three decisions:</p>
<ol style="list-style-type: decimal">
<li>What financial variables to use</li>
<li>What time span to use</li>
<li>Which tickers to use</li>
</ol>
<p>The data set was compiled from various
data sources including <a href="https://finance.yahoo.com">Yahoo
Finance</a>,
<a href="https://www.sec.gov/edgar/searchedgar/companysearch.html">EDGAR</a>,
and others. I compiled the data using
several R scripts that involve web
scraping and data cleaning. I cannot
attest to the quality of the data.</p>
</div>
<div id="exploratory-data-analysis" class="section level2">
<h2>Exploratory data analysis</h2>
<p>Let’s inspect the data for missing
values and view the variable
distributions</p>
<div id="missing-data" class="section level3">
<h3>Missing data</h3>
<p>A common problem with large data sets is
missing data. Our goal is to find a
subset of the data that is complete so
that we can avoid having to do
imputation. Importantly, some variables
are raw data figures and others are
ratios derived from the raw data. We
will choose a group of variables among
the derived ratios to serve as input
variables.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Inspect missing data</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>start_date <span class="ot">&lt;-</span> <span class="st">&quot;2010-12-31&quot;</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>end_date <span class="ot">&lt;-</span> <span class="st">&quot;2019-12-31&quot;</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>tickers_with_full_dates <span class="ot">&lt;-</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>      ratios_long <span class="sc">%&gt;%</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">distinct</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">group_by</span>(ticker) <span class="sc">%&gt;%</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(dplyr<span class="sc">::</span><span class="fu">first</span>(fundamentals_date) <span class="sc">&lt;=</span> start_date <span class="sc">&amp;</span> dplyr<span class="sc">::</span><span class="fu">last</span>(fundamentals_date) <span class="sc">&gt;=</span> end_date) <span class="sc">%&gt;%</span> </span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">distinct</span>(ticker) <span class="sc">%&gt;%</span> </span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>      <span class="fu">pull</span>()</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Choose ratios that contain the desired date range</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>ratios_filtered <span class="ot">&lt;-</span> </span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>      ratios_long <span class="sc">%&gt;%</span> </span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(ticker <span class="sc">%in%</span> tickers_with_full_dates) <span class="sc">%&gt;%</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(<span class="fu">between</span>(fundamentals_date, <span class="fu">as.Date</span>(start_date), <span class="fu">as.Date</span>(end_date))) <span class="sc">%&gt;%</span> </span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>      <span class="fu">distinct</span>()</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Get ratios of missing values</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>ratios_na <span class="ot">&lt;-</span></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>      ratios_filtered <span class="sc">%&gt;%</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(<span class="sc">-</span>sector_yhoo, <span class="sc">-</span>fundamentals_date, <span class="sc">-</span>sector_yhoo) <span class="sc">%&gt;%</span> </span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Replace any infinity values with NA</span></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate</span>(<span class="at">value =</span> <span class="fu">ifelse</span>(<span class="fu">is.finite</span>(value), value, <span class="cn">NA</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>      <span class="fu">group_by</span>(ticker, field) <span class="sc">%&gt;%</span> </span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>      <span class="co"># summarize(across(where(is.numeric), ~sum(is.na(.x)) / n())) %&gt;%</span></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate</span>(<span class="at">na_ratio =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(value)) <span class="sc">/</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>      <span class="fu">distinct</span>()</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a><span class="co"># See which tickers have at least 10 ratios with less than 10% of values missing</span></span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>tickers_with_low_na <span class="ot">&lt;-</span></span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>      ratios_na <span class="sc">%&gt;%</span></span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>      <span class="fu">distinct</span>(ticker, field, na_ratio) <span class="sc">%&gt;%</span> </span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>      <span class="fu">group_by</span>(ticker) <span class="sc">%&gt;%</span></span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(na_ratio <span class="sc">&lt;</span> <span class="fl">0.1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>      <span class="fu">count</span>(ticker) <span class="sc">%&gt;%</span> </span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(n <span class="sc">==</span> <span class="fu">max</span>(n)) <span class="sc">%&gt;%</span> </span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>      <span class="fu">pull</span>(ticker)</span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(tickers_with_low_na)</span></code></pre></div>
<pre><code>## [1] 431</code></pre>
<p>There are
431 tickers
with at least 10 ratios having less than
10% of values missing.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View the ratio of missing data by ticker and field (for a sample of the data)</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>ratios_na <span class="sc">%&gt;%</span> </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Choose 10 random tickers</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(ticker <span class="sc">%in%</span> <span class="fu">sample</span>(tickers_with_low_na, <span class="dv">10</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>      <span class="co"># mutate(font_color = factor(ifelse(na_ratio == 0, &quot;white&quot;, &quot;black&quot;))) %&gt;% </span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ggplot</span>(<span class="fu">aes</span>(ticker, field, <span class="at">fill =</span> na_ratio)) <span class="sc">+</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_tile</span>(<span class="at">color =</span> <span class="st">&quot;darkgray&quot;</span>, <span class="at">lwd =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>      <span class="co"># geom_text(aes(label = percent_format(accuracy = 1)(na_ratio)), color = &quot;black&quot;, size = 4) +</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">&quot;white&quot;</span>, <span class="at">high =</span> <span class="st">&quot;red&quot;</span>, <span class="at">name =</span> <span class="st">&quot;&quot;</span>, <span class="at">labels =</span> percent) <span class="sc">+</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>      <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Percent of Missing Values&quot;</span>, <span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> <span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>      <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>      <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">3</span>),</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.key.height =</span> <span class="fu">unit</span>(<span class="dv">1</span>, <span class="st">&quot;cm&quot;</span>),</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.key.width =</span> <span class="fu">unit</span>(<span class="fl">0.2</span>, <span class="st">&quot;cm&quot;</span>))</span></code></pre></div>
<p><img src="/post/2021-07-27-logistic-regression-with-stock-returns_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>It looks like the variable
<strong>sga_index</strong> has a significant amount of missing
values. We will try to find data without
missing values and use it in the
classification model.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># See which fields have complete data for some tickers</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>fields_to_use <span class="ot">&lt;-</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>      ratios_na <span class="sc">%&gt;%</span> </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(na_ratio <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">distinct</span>(ticker, field, na_ratio) <span class="sc">%&gt;%</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">distinct</span>(field) <span class="sc">%&gt;%</span> </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">pull</span>()</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>tickers_to_use <span class="ot">&lt;-</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>      ratios_na <span class="sc">%&gt;%</span> </span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>      <span class="fu">distinct</span>(ticker, field, na_ratio) <span class="sc">%&gt;%</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(field <span class="sc">%in%</span> fields_to_use) <span class="sc">%&gt;%</span> </span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(na_ratio <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>      <span class="fu">count</span>(ticker, <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(n <span class="sc">==</span> <span class="fu">max</span>(n)) <span class="sc">%&gt;%</span> </span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>      <span class="fu">pull</span>(ticker)</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(tickers_to_use)</span></code></pre></div>
<pre><code>## [1] 189</code></pre>
<p>There are 189
tickers with no missing values. These
tickers will be used to develop a
classification model.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>ratios_final <span class="ot">&lt;-</span>  </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>      ratios_filtered <span class="sc">%&gt;%</span> </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Select fields with complete data</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(field <span class="sc">%in%</span> fields_to_use) <span class="sc">%&gt;%</span> </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Select tickers with complete data</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(ticker <span class="sc">%in%</span> tickers_to_use) <span class="sc">%&gt;%</span> </span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">distinct</span>()</span></code></pre></div>
</div>
</div>
<div id="variable-selection" class="section level2">
<h2>Variable selection</h2>
<p>We will select a group of the ratio-type
variables as features and attempt to
predict the six-month stock return for
one or more public companies.</p>
<p>The variables <strong>current_ratio</strong>,
<strong>lt_debt_ratio_pct_chg_1Y</strong>,
<strong>sales_growth_index</strong>,
<strong>leverage_index</strong>,
<strong>scaled_total_accruals</strong>,
<strong>scaled_net_operating_assets</strong>,
<strong>asset_turnover</strong>,
<strong>total_accruals_to_total_assets</strong>, and
<strong>free_cash_flow_to_assets</strong> will be
used to predict <strong>adj_return_6M</strong>, which will
transformed from a numeric to a nominal variable.</p>
<div id="feature-variables" class="section level3">
<h3>Feature variables</h3>
<p><span class="math inline">\(current\_ratio = \frac{total\,current\,assets_t} {total\,current\,liabilities_t}\)</span></p>
<ul>
<li><strong>current_ratio</strong> measures the
amount of current assets relative to
current liabilities.</li>
</ul>
<p><span class="math inline">\(lt\_debt\_ratio\_pct\_chg\_1Y = \Delta \frac{total\, liabilities_t - total\,current\,liabilities_t}{total\,assets_t}-1\)</span></p>
<ul>
<li><strong>lt_debt_ratio_pct_chg_1Y</strong>
measures the percent change in the
long-term debt ratio. Growth in this
ratio can be good for healthy
companies and bad for others.</li>
</ul>
<p><span class="math inline">\(sales\_growth\_index = \frac{revenue_t} {revenue_{t-12}}\)</span></p>
<ul>
<li><strong>sales_growth_index</strong> is the ratio of revenue in year <em>t</em> to that of the
prior year. A growing value
indicates sales growth.</li>
</ul>
<p><span class="math inline">\(leverage\_index = \frac{debt \, ratio_t} {debt \, ratio_{t-12}}\)</span></p>
<ul>
<li><strong>leverage_index</strong> measures the
value of the debt ratio relative to
its value the year before. A higher
index means the debt is growing
relative to assets.</li>
</ul>
<p><span class="math inline">\(scaled\_total\_accruals = \frac{(total\,current\,assets_t - cash\,and\,short\,term\,investments_t) - (total\,current\,liabilities_t - \Delta short-term\,portion\,of\,long\,term\,debt_t) - depreciation\,amortization_t)} {total\,assets_t}\)</span></p>
<ul>
<li><strong>scaled_total_accruals</strong> measures
the amount of non-cash accumulated
current assets relative total
assets. Higher scaled total accruals
can indicate a higher likelihood of
earnings manipulation.</li>
</ul>
<p><span class="math inline">\(scaled\_net\_operating\_assets = \frac{(total\,assets - cash \, and \, short\,term\,investments) - (total\,liabilities - total\,debt))} {total\,assets}\)</span></p>
<ul>
<li><strong>scaled_net_operating_assets</strong>
measures the proportion of assets
that are used to generate sales less
the proportion of liabilities that
are used to finance those assets.
Higher scaled net operating assets
is a sign of relatively low asset
accruals on the balance sheet, a
good sign.</li>
</ul>
<p><span class="math inline">\(asset\_turnover = \frac{annual \, revenue_t} {total \, assets_t}\)</span></p>
<ul>
<li><strong>asset_turnover</strong> measures a firm’s
ability to turn assets into sales
revenue. A higher value indicates
more efficient use of assets in
generating sales revenue.</li>
</ul>
<p><span class="math inline">\(total\_accruals\_to\_total\_assets = \frac{(\Delta working\,cap\,ex\,cash_t - depreciation\,amortization_t)} {total\,assets_t}\)</span></p>
<ul>
<li><strong>total_accruals_to_total_assets</strong>
measures the relative change in
accruals. An increasing value
indicates increasing non-cash assets
relative to total assets and a
higher likelihood of earnings
manipulation.</li>
</ul>
<p><span class="math inline">\(free\_cash\_flow\_to\_assets = \frac{free\,cash\,flow_t} {total\,assets_t}\)</span></p>
<ul>
<li><strong>free_cash_flow_to_assets</strong>
measures the amount of cash flow
available to stock and bond holders
relative to total assets.</li>
</ul>
</div>
<div id="response-variable" class="section level3">
<h3>Response variable</h3>
<p><span class="math inline">\(adj\_return\_6M\_\_\_9M\_ forward = log(\frac{adjusted\,price_{t+9}} {adjusted\,price_{t+3}})\)</span></p>
<ul>
<li><strong>adj_return_6M___9M_forward</strong>
represents the 6-month stock price
return using adjusted prices for a
period ending nine months in the
future. In reality, the raw data is
not published until several weeks or
months after the close of the
company’s fiscal period, so it is
important to assume that the
financial ratios aren’t available to
decision makers until a sufficient
time after their public disclosure.
In this case, we assumed decision
makers will have full access to the
financial data three months after
the close of the fiscal period.</li>
</ul>
</div>
</div>
<div id="data-cleaning" class="section level2">
<h2>Data cleaning</h2>
<p>We will select the desired variables and
create a new variable.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>ratios <span class="ot">&lt;-</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>      ratios_final <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>      <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> <span class="st">&quot;field&quot;</span>, <span class="at">values_from =</span> <span class="st">&quot;value&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Get the 9-month forward values of the adj_return_6M variable</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate</span>(<span class="at">adj_return_6M_forward_9M =</span> <span class="fu">lead</span>(adj_return_6M, <span class="dv">9</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(<span class="sc">-</span>adj_return_6M)</span></code></pre></div>
<p>This leaves us with 189
tickers to choose from. We will choose
all companies in the industrials sector.</p>
<p>Now, we will choose the final data
subset to feed into the logistic model.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>ratios_filtered <span class="ot">&lt;-</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>      ratios <span class="sc">%&gt;%</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>      <span class="fu">left_join</span>(ratios_data <span class="sc">%&gt;%</span> <span class="fu">select</span>(ticker, fundamentals_date, sector_yhoo) <span class="sc">%&gt;%</span> </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">distinct</span>(ticker, sector_yhoo)) <span class="sc">%&gt;%</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(sector_yhoo <span class="sc">==</span> <span class="st">&quot;industrials&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate</span>(<span class="at">return_sign =</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(adj_return_6M_forward_9M <span class="sc">&gt;</span> <span class="dv">0</span>, <span class="st">&quot;pos&quot;</span>, <span class="st">&quot;neg&quot;</span>), <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;pos&quot;</span>, <span class="st">&quot;neg&quot;</span>))) <span class="sc">%&gt;%</span> </span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">arrange</span>(fundamentals_date) <span class="sc">%&gt;%</span> </span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(<span class="sc">-</span>sector_yhoo, <span class="sc">-</span>adj_return_6M_forward_9M)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>data_count <span class="ot">&lt;-</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>      ratios_filtered <span class="sc">%&gt;%</span> </span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>      <span class="fu">count</span>(return_sign) <span class="sc">%&gt;%</span> </span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>      janitor<span class="sc">::</span><span class="fu">adorn_totals</span>(<span class="st">&quot;row&quot;</span>)</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>data_count</span></code></pre></div>
<pre><code>##  return_sign    n
##          pos 3045
##          neg 1315
##        Total 4360</code></pre>
<div id="data-balance" class="section level3">
<h3>Data balance</h3>
<p>The response variable (return_sign) has over
twice as many positive values
(3,045)
than negative values
(1,315).
This could skew the model results, so we
will downsample the data in order to
create balanced response outcomes.</p>
<p>Now, let’s look at the distributions of
each variable through boxplots.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View distributions</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>ratios_filtered <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(<span class="sc">-</span>return_sign, <span class="sc">-</span>ticker) <span class="sc">%&gt;%</span> </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">pivot_longer</span>(<span class="sc">-</span>fundamentals_date, <span class="at">names_to =</span> <span class="st">&quot;field&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate</span>(<span class="at">median_x =</span> <span class="fu">median</span>(value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> value, <span class="at">y =</span> <span class="fu">reorder</span>(field, median_x), <span class="at">fill =</span> field)) <span class="sc">+</span> </span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Boxplots of model variables&quot;</span>,</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> <span class="st">&quot;&quot;</span>, <span class="at">x =</span> <span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">coord_cartesian</span>(<span class="at">clip =</span> <span class="st">&quot;off&quot;</span>) <span class="sc">+</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>      <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>      <span class="fu">theme</span>(<span class="at">axis.title.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="sc">-</span><span class="dv">3</span>),</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>            <span class="at">panel.border =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>            <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>            <span class="at">panel.grid.minor.x =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<p><img src="/post/2021-07-27-logistic-regression-with-stock-returns_files/figure-html/unnamed-chunk-7-1.png" width="768" /></p>
<p>There appears to be outliers several feature
variables, including asset_turnover. They could be due to once-in-a-lifetime
anamolies or data input errors.</p>
</div>
<div id="clean-up-outliers" class="section level3">
<h3>Clean Up Outliers</h3>
<p>We will loosely define outliers as
values in less than the 0.005 quantile
or greater than the 0.995 quantile for
all variables. We will replace extreme values with the median
values per field.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace outliers with median values per field</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>ratios_cleaned <span class="ot">&lt;-</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>      ratios_filtered <span class="sc">%&gt;%</span> </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">distinct</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">pivot_longer</span>(<span class="sc">-</span><span class="fu">c</span>(fundamentals_date, ticker, return_sign), <span class="at">names_to =</span> <span class="st">&quot;field&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">group_by</span>(field) <span class="sc">%&gt;%</span> </span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Replace extreme values with median of the field</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate</span>(<span class="at">value =</span> <span class="fu">ifelse</span>(value <span class="sc">&lt;</span> <span class="fu">quantile</span>(value, .<span class="dv">005</span>), <span class="fu">median</span>(value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), value),</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">value =</span> <span class="fu">ifelse</span>(value <span class="sc">&gt;</span> <span class="fu">quantile</span>(value, .<span class="dv">995</span>), <span class="fu">median</span>(value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), value)) <span class="sc">%&gt;%</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> field, <span class="at">values_from =</span> value)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>ratios_cleaned <span class="sc">%&gt;%</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(<span class="sc">-</span>return_sign, <span class="sc">-</span>ticker) <span class="sc">%&gt;%</span> </span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>      <span class="fu">pivot_longer</span>(<span class="sc">-</span><span class="fu">c</span>(fundamentals_date), <span class="at">names_to =</span> <span class="st">&quot;variable&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>      <span class="fu">group_by</span>(variable) <span class="sc">%&gt;%</span> </span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate</span>(<span class="at">median_x =</span> <span class="fu">median</span>(value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> value, <span class="at">y =</span> <span class="fu">reorder</span>(variable, median_x), <span class="at">fill =</span> variable)) <span class="sc">+</span> </span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>      <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Boxplots of model variables&quot;</span>,</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> <span class="st">&quot;&quot;</span>, <span class="at">x =</span> <span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>      <span class="fu">coord_cartesian</span>(<span class="at">clip =</span> <span class="st">&quot;off&quot;</span>) <span class="sc">+</span></span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>      <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>      <span class="fu">theme</span>(<span class="at">axis.title.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>            <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="sc">-</span><span class="dv">3</span>),</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>            <span class="at">panel.border =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>            <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>            <span class="at">panel.grid.minor.x =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<p><img src="/post/2021-07-27-logistic-regression-with-stock-returns_files/figure-html/Remove%20Outliers-1.png" width="768" /></p>
<p>After removing extreme values, the
variables contain more realistic values
and the fitted logistic model will
likely be more robust and less affected
by extreme values.</p>
</div>
</div>
<div id="statistical-modeling" class="section level2">
<h2>Statistical modeling</h2>
<p>We will use a logistic model with the
four numeric feature variables mentioned
earlier and the six-month stock return
as the dependent variable.</p>
<div id="split-the-data-into-training-and-test-sets" class="section level3">
<h3>Split the data into training and test sets</h3>
<p>In order to test the results of our
model, we will split the data into two
groups, a training set (75% of the data)
and a test set (25% of the data). The
logistic model will be applied to the
training set and the resulting model
will be evaluated on the remaining 25%.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Split data</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>data_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(ratios_cleaned <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>ticker, <span class="sc">-</span>fundamentals_date))</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>data_train <span class="ot">&lt;-</span> <span class="fu">training</span>(data_split)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>data_test <span class="ot">&lt;-</span> <span class="fu">testing</span>(data_split)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the model and feature engineering steps</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>ratios_recipe <span class="ot">&lt;-</span> </span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">recipe</span>(return_sign <span class="sc">~</span> ., <span class="at">data =</span> data_train) <span class="sc">%&gt;%</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Filter out variables that are too correlated with each other</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>      <span class="fu">step_corr</span>(<span class="fu">all_predictors</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Remove any numeric variables that have zero variance</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>      <span class="fu">step_zv</span>(<span class="fu">all_numeric</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Downsample the data, since there are significantly unbalanced data in the outcomes variable</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>      <span class="co"># If we don&#39;t do this, our model will learn very effectively about how to predict one case rather than both</span></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>      themis<span class="sc">::</span><span class="fu">step_downsample</span>(return_sign)</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare the data</span></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>data_prep <span class="ot">&lt;-</span> ratios_recipe <span class="sc">%&gt;%</span> <span class="fu">prep</span>()</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply transformations</span></span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>data_juiced <span class="ot">&lt;-</span> data_prep <span class="sc">%&gt;%</span> <span class="fu">juice</span>()</span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>data_count <span class="ot">&lt;-</span></span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>      data_juiced <span class="sc">%&gt;%</span> </span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>      <span class="fu">count</span>(return_sign) <span class="sc">%&gt;%</span> </span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>      janitor<span class="sc">::</span><span class="fu">adorn_totals</span>(<span class="st">&quot;row&quot;</span>)</span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a>data_count</span></code></pre></div>
<pre><code>##  return_sign    n
##          pos  971
##          neg  971
##        Total 1942</code></pre>
<p>The downsampling reduced the data to
1,942
observations with equal number of
<strong>pos</strong> and <strong>neg</strong> values in the
response variable (return_sign). This
will prevent model results that are
biased due to unbalanced response
variable values in the testing data.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply a logistic regression model</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>lr_model <span class="ot">&lt;-</span> </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>      <span class="fu">logistic_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">set_engine</span>(<span class="st">&quot;glm&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">set_mode</span>(<span class="st">&quot;classification&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Fit the model</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">fit</span>(return_sign <span class="sc">~</span> ., <span class="at">data =</span> data_juiced)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>lr_model</span></code></pre></div>
<pre><code>## parsnip model object
## 
## Fit time:  40ms 
## 
## Call:  stats::glm(formula = return_sign ~ ., family = stats::binomial, 
##     data = data)
## 
## Coefficients:
##                    (Intercept)                   current_ratio  
##                         0.5706                          0.1315  
##          scaled_total_accruals     scaled_net_operating_assets  
##                        -1.0280                          0.9143  
## total_accruals_to_total_assets        free_cash_flow_to_assets  
##                        -1.1913                          1.6947  
##       lt_debt_ratio_pct_chg_1Y                  asset_turnover  
##                         0.1242                          0.2496  
##             sales_growth_index                  leverage_index  
##                         0.5633                         -2.2487  
## 
## Degrees of Freedom: 1941 Total (i.e. Null);  1932 Residual
## Null Deviance:       2692 
## Residual Deviance: 2622  AIC: 2642</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(lr_model, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(term)</span></code></pre></div>
<pre><code>## [1] &quot;current_ratio&quot;               &quot;scaled_net_operating_assets&quot;
## [3] &quot;free_cash_flow_to_assets&quot;    &quot;asset_turnover&quot;             
## [5] &quot;sales_growth_index&quot;          &quot;leverage_index&quot;</code></pre>
<p>The logistic regression shows that the
variables <strong>current_ratio</strong>,
<strong>sales_growth_index</strong>,
<strong>leverage_index</strong>,
<strong>scaled_net_operating_assets</strong>,
<strong>asset_turnover</strong>, and
<strong>free_cash_flow_to_assets</strong> have
significant p-values.</p>
<p>We will fit a new logistic model using
these variables.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the model and feature engineering steps</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>model_recipe <span class="ot">&lt;-</span> <span class="fu">recipe</span>(return_sign <span class="sc">~</span> current_ratio <span class="sc">+</span> sales_growth_index <span class="sc">+</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>                             leverage_index <span class="sc">+</span> scaled_net_operating_assets <span class="sc">+</span> </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>                             asset_turnover <span class="sc">+</span> free_cash_flow_to_assets,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">data =</span> data_juiced)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare the data</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>data_prep <span class="ot">&lt;-</span> ratios_recipe <span class="sc">%&gt;%</span> <span class="fu">prep</span>()</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply transformations</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>data_juiced <span class="ot">&lt;-</span> data_prep <span class="sc">%&gt;%</span> <span class="fu">juice</span>()</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply a logistic regression model</span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>fitted_logistic_model <span class="ot">&lt;-</span> </span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>      <span class="fu">logistic_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>      <span class="fu">set_engine</span>(<span class="st">&quot;glm&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>      <span class="fu">set_mode</span>(<span class="st">&quot;classification&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Fit the model</span></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>      <span class="fu">fit</span>(return_sign <span class="sc">~</span> ., <span class="at">data =</span> data_juiced)</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(fitted_logistic_model, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(term)</span></code></pre></div>
<pre><code>## [1] &quot;current_ratio&quot;               &quot;scaled_net_operating_assets&quot;
## [3] &quot;free_cash_flow_to_assets&quot;    &quot;asset_turnover&quot;             
## [5] &quot;sales_growth_index&quot;          &quot;leverage_index&quot;</code></pre>
</div>
</div>
<div id="interpret-results" class="section level2">
<h2>Interpret results</h2>
<p>The variables <strong>current_ratio</strong>,
<strong>sales_growth_index</strong>,
<strong>leverage_index</strong>,
<strong>scaled_net_operating_assets</strong>,
<strong>asset_turnover</strong>, and
<strong>free_cash_flow_to_assets</strong> still have
significant p-values so they will be used
in the final model.</p>
</div>
<div id="final-model" class="section level2">
<h2>Final Model</h2>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply final logistic regression model</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>final_logistic_model <span class="ot">&lt;-</span> </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>      <span class="fu">logistic_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">set_engine</span>(<span class="st">&quot;glm&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">set_mode</span>(<span class="st">&quot;classification&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Fit the model</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">fit</span>(return_sign <span class="sc">~</span> current_ratio <span class="sc">+</span> sales_growth_index <span class="sc">+</span> </span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>                             leverage_index <span class="sc">+</span> scaled_net_operating_assets <span class="sc">+</span> </span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>                             asset_turnover <span class="sc">+</span> free_cash_flow_to_assets, </span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> data_juiced)</span></code></pre></div>
<div id="model-predictions" class="section level3">
<h3>Model predictions</h3>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Class prediction</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>pred_class <span class="ot">&lt;-</span> <span class="fu">predict</span>(final_logistic_model, <span class="at">new_data =</span> data_test, <span class="at">type =</span> <span class="st">&quot;class&quot;</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Prediction Probabilities</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>pred_probs <span class="ot">&lt;-</span> <span class="fu">predict</span>(final_logistic_model, <span class="at">new_data =</span> data_test, <span class="at">type =</span> <span class="st">&quot;prob&quot;</span>)</span></code></pre></div>
</div>
<div id="model-evaluation" class="section level3">
<h3>Model evaluation</h3>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>model_results <span class="ot">&lt;-</span> </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>      data_test <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(return_sign) <span class="sc">%&gt;%</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">bind_cols</span>(pred_class, pred_probs)</span></code></pre></div>
<p>The following definitions will apply:</p>
<ul>
<li>TP = True Positive (prediction of
positive return and actual positive
return)</li>
<li>FP = False Positive (prediction of
positive return, but actual negative
return)</li>
<li>TN = True Negative (prediction of
negative return and actual negative
return)</li>
<li>FN = False Negative (prediction of
negative return, but actual positive
return)</li>
</ul>
<div id="confusion-matrix" class="section level4">
<h4>Confusion matrix</h4>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>cf <span class="ot">&lt;-</span> <span class="fu">conf_mat</span>(model_results, <span class="at">truth =</span> return_sign, <span class="at">estimate =</span> .pred_class)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(cf, <span class="at">type =</span> <span class="st">&quot;heatmap&quot;</span>) <span class="sc">+</span> <span class="fu">scale_fill_gradient2</span>(<span class="at">high =</span> <span class="st">&quot;lightblue&quot;</span>)</span></code></pre></div>
<p><img src="/post/2021-07-27-logistic-regression-with-stock-returns_files/figure-html/Confusion%20Matrix-1.png" width="384" /></p>
</div>
<div id="accuracy" class="section level4">
<h4>Accuracy</h4>
<p>Accuracy measures the model’s ability to
make a correct positive case or negative
case.</p>
<p><span class="math inline">\(Accuracy = \frac{TP + TN}{ TN + FN + TP + FP}\)</span></p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Accuracy</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>accuracy <span class="ot">&lt;-</span> model_results <span class="sc">%&gt;%</span> <span class="fu">accuracy</span>(return_sign, .pred_class)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>accuracy</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   .metric  .estimator .estimate
##   &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
## 1 accuracy binary         0.560</code></pre>
<p>The accuracy is about
0.56,
meaning the model correctly predicted a
positive case or negative case
56%
of the time.</p>
</div>
<div id="sensitivity" class="section level4">
<h4>Sensitivity</h4>
<p>Sensitivity measures the model’s ability
to correctly classify positive cases.</p>
<p><span class="math inline">\(Sensitivity = \frac{TP}{TP + FN}\)</span></p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sensitivity</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>sensitivity <span class="ot">&lt;-</span> model_results <span class="sc">%&gt;%</span> <span class="fu">sens</span>(return_sign, .pred_class)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>sensitivity</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 sens    binary         0.574</code></pre>
<p>The sensitivity is about
0.57,
meaning the model correctly predicted
positive cases
57%
of the time.</p>
</div>
<div id="specificity" class="section level4">
<h4>Specificity</h4>
<p>Specificity measures the model’s ability
to correctly classify negative cases.</p>
<p><span class="math inline">\(Specificity = \frac{TN}{TN + FP}\)</span></p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Specificity</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>specificity <span class="ot">&lt;-</span> yardstick<span class="sc">::</span><span class="fu">spec</span>(model_results, return_sign, .pred_class)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>specificity</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 spec    binary         0.529</code></pre>
<p>The specificity is
0.53,
meaning the model correctly classified
negative cases
53%
of the time.</p>
</div>
</div>
</div>
<div id="final-results" class="section level2">
<h2>Final results</h2>
<p>The model did an overall mediocre job of
predicting whether forward-looking six-month stock
returns for industrial companies over
the period December 31, 2010 to December 31, 2019 are
positive or negative using
<strong>current_ratio</strong>,
<strong>sales_growth_index</strong>,
<strong>leverage_index</strong>,
<strong>scaled_net_operating_assets</strong>,
<strong>asset_turnover</strong>, and
<strong>free_cash_flow_to_assets</strong> as input
variables. The model correctly predicted
a positive return about
57%
of the time and correctly predicted a
negative return about
53%
of the time.</p>
</div>
<div id="discussion" class="section level2">
<h2>Discussion</h2>
<p>This model is did a poor job at predicting forward-looking 6-month
stock returns for the period ending nine months in the future when using a
particular subset of industrial sector companies. An accuracy of 80% of higher
would have been acceptable to justify further investigation as well as<br />
formulation and testing of a trading strategy. Moreover, this model does not
distinguish low positive returns from high positive returns and instead lumps
them together as “positive returns.” Undoubtedly, an investor would like to
know if a model is good at predicting high positive returns (or negative returns
for that matter) rather than just positive (negative) returns. People, not just
investors, have psychological biases, both cognitive and emotional. For example
a 100% percent positive return to a portfolio is a huge benefit to the investor
but a 100% negative return can be fatal to a portfolio, leading the investor to
place more weight on a model’s ability to predict negative returns. The success
of this model was based on its ability to equally predict positive returns or
negative returns and on that basis, it did a poor job.</p>
</div>
