---
title: Reading a 10-K
author: Aaron Hardy
date: '`r Sys.Date()`'
slug: []
categories:
  - Financial Statements
tags:
  - 10-K
description: ''
featured: ''
featuredalt: ''
featuredpath: ''
linktitle: ''
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, cache = TRUE)
```

## Reading a 10-K

Every year public companies in the U.S.
are required by law to produce a
financial report containing financial
data, risk disclosures, and related
information. Over the years, 10-Ks
appear to be growing more complex as
companies dump more and more information
into them. This is partly done to reduce
the risk that investors or other
stakeholders will accuse the company of
failing to disclose relevant and
material information. Meanwhile,
investors have to wain through dozens of
pages of dense information trying to
glean out the critical pieces.

I am a big fan of Aswath Damadoran,
professor of finance at the Stern School
of Business at New York University. He
produced a video about reading 10-Ks
which you can see
[here](https://m.youtube.com/watch?v=UzUJzdn7c2w "Video link - valuation").
I will discuss some of the main points
which I will use when analyzing stocks
in subsequent posts.
